version: '3.8'

services:
  db:
    image: postgres:15
    container_name: weather-db
    restart: always
    environment:
      POSTGRES_DB: weather
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - weather-network

  api:
    build: .
    container_name: weather-api
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DB_NAME: weather
      USER: user
      PASSWORD: password
      HOST: db
      PORT: 5432
    networks:
      - weather-network

volumes:
  pgdata:

networks:
  weather-network:
